### ISSUE TITLE
Doesn't work together with gulp-gitbook

### ISSUE THREAD

**Issue by acierto** [DevExpress/gulp-testcafe#7]
Hey, thank you for a nice plugin!

Today I added as I thought for myself an innocent change to a project and surprisingly found out that my change broke my e2e tests on testcafe. 

https://circleci.com/gh/acierto/type-system-explorer/34

As you can see from logs gulp-testcafe just crashes on stack overflow. 

After some of investigation I found out that this line does it.

```
import gulpGitbook from 'gulp-gitbook';
```

Of course I can for now to change my code to:
```
gulp.task('generate-docs', (cb) => {
    require('gulp-gitbook')(srcDocsDir, cb);
});
```
so importing of gulp-gitbook will not affect the global context.

But fix of this problem is very appreciated!

**Comment by AlexanderMoskovkin** [comment]
Hi @acierto,

I've investigated the issue.
TestCafe uses the [css](https://github.com/reworkcss/css) module to parse css files (its dependency `testcafe-hammerhead` uses it, to be precise). The `gulp-gitbook` module uses `gitbook` which uses some other dependencies which use the [asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js) module. 
When you require the `gulp-gitbook` module it executes the `asciidoctor.js` module code. As a result this breaks the `css` module when we call it [here](https://github.com/DevExpress/testcafe-hammerhead/blob/67618b251aa3fcf9958870b9fd0419804203c9d8/src/shadow-ui/create-shadow-stylesheet.js#L26).
I've added this info into the issue in the `asciidoctor.js` repository: https://github.com/asciidoctor/asciidoctor.js/issues/299#issuecomment-376575994.

Unfortunately it seems we can't fix it on our side because we can't get rid of the `css` module. So while it's not fixed you can use your workaround.
